apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: visb3ogte-python 
  janus-idp.io/tekton: visb3ogte-python
  backstage.io/kubernetes-id: visb3ogte-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: visb3ogte-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml