apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: visb3ogte-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: visb3ogte-python 
  name: visb3ogte-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: visb3ogte-python 
